spring.application.name=springboot-thymeleaf-crud
# Đổi port sang 8081 để tránh trùng với port 8080 của dự án JSP cũ
server.port=8081

# Cấu hình kết nối SQL Server với Database mới SpringBootThymeleafDB
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SpringBootThymeleafDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cấu hình Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Cấu hình tải file ảnh đại diện (Multipart File Upload)
app.upload.dir=uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
